### ISSUE TITLE
ElSelect option的value不能为数字

### ISSUE THREAD

**Issue by John60676** [xuliangzhan/vxe-table-plugin-element#15]
### （必填）请填写问题描述 Describe the bug

 ElSelect option的value如果是数字的话，筛选按钮不能点击

### （必填）请填写能重现问题的链接

https://codesandbox.io/s/vxe-table-ceshide-demo-pt4wg?file=/src/views/Demo1.vue

### 填写报错信息或截图 Error message or screenshots

 option.value为数字时的效果

![Kapture 2020-04-23 at 17 37 50](https://user-images.githubusercontent.com/21698973/80084312-47cf4080-8589-11ea-8d5e-1c5e74ae6995.gif)

option.value为字符串时的效果

![Kapture 2020-04-23 at 17 43 50](https://user-images.githubusercontent.com/21698973/80084898-1acf5d80-858a-11ea-9075-e8c4e6cb854a.gif)

### （必填）请填写期望的结果 Expected behavior

 option.value为数字时的筛选按钮也能正常使用

**Comment by xuliangzhan** [comment]
建议更新到最新版本试试

**Comment by John60676** [comment]
1.8.7已修复
