### ISSUE TITLE
Unknown custom element

### ISSUE THREAD

**Issue by mehdibahrami** [xuliangzhan/vxe-table-plugin-element#16]
I don't know what is the problem but I can't use the cell demo that you provided on the readme.
```
import Vue from 'vue'
import 'xe-utils'
import VXETable from 'vxe-table'
import 'vxe-table/lib/index.css'
import VXETablePluginElement from 'vxe-table-plugin-element'
import 'vxe-table-plugin-element/dist/style.css'
import VueI18n from 'vue-i18n'
import enUS from 'vxe-table/lib/locale/lang/en-US'

Vue.use(VueI18n)
const messages = {
  en_US: {
    ...enUS
  }
}

const i18n = new VueI18n({
  locale: 'en_US',
  messages
})

Vue.use(VXETable, {
  i18n: key => i18n.t(key)
})

VXETable.use(VXETablePluginElement)
```
![Screen Shot 2020-05-02 at 21 06 22](https://user-images.githubusercontent.com/63710663/80869989-cda16900-8cb8-11ea-9d49-793705e7357b.png)

Could you please help me? I need to add a multiple select to my modal form and because of that I wanna add element-ui for using that.

**Comment by xuliangzhan** [comment]
You should check if you use  [element-ui](https://element.eleme.cn/#/zh-CN/component/quickstart).
