### ISSUE TITLE
如何增加其他的筛选，例如ElSelect筛选

### ISSUE THREAD

**Issue by fishman132yangbo** [xuliangzhan/vxe-table-plugin-element#3]
**这个新特性和一个问题相关吗？简单描述下，比如我什么场景下，需要解决什么问题，发现表格不支持这个功能 Is your feature request related to a problem? Please describe.**

**描述下，你希望得到的什么解决方案 Describe the solution you'd like**

**是否有不错的替代方案 Describe alternatives you've considered**

**Comment by xuliangzhan** [comment]
筛选干嘛要用 ElSelect，这不是多此一举吗？

**Comment by fishman132yangbo** [comment]
> 筛选干嘛要用ElSelect，这不是多此一举吗？
感谢作者，昨天提的问题，晚上就解决了。麻烦抽个时间把ElCascader也加上呗。数据有的有层次结构。很多系统应该都有这种需求。

**Comment by jianliulin** [comment]
ElCascader已经支持了，
