### ISSUE TITLE
ElUpload feature

### ISSUE THREAD

**Issue by furqon** [xuliangzhan/vxe-table-plugin-element#4]
are there any posibilities to add ElUpload editable row?

**Comment by xuliangzhan** [comment]
Sorry, the upload component is not suitable for cells, you can use a custom template

**Comment by furqon** [comment]
actually ElUpload is still suitable for cells. :D
- add button upload on edit
- after upload response successful set the cell value to filename or path.. :)

anyway, thank you for pointing me the custom templates. nice to have that custom component

**Comment by xuliangzhan** [comment]
Could you provide some relevant links for reference? Because I don't know what functions the upload component should implement in the cell,  I can't be sure whether it can be supported or not?
https://jsfiddle.net/51ztmovb/

**Comment by furqon** [comment]
Thank you for the feedback.. sorry I'm trying to make working jsfiddle on this, but cannot. Here is what I do in my local [screen reader](https://webm.red/xDOu) 

After getting response, probably replace the upload button with response filename from server.
It takes component from https://element.eleme.io/#/en-US/component/upload 

Here is my custom template


```
import VXETable from 'vxe-table'

VXETable.renderer.add('ElUpload', {
  autofocus: '.my-cell',
  renderEdit (h, editRender, { row, column }) {
    return [
      <el-upload class="upload-demo" ref="upload" action="http://localhost:8000/api/upload"><el-button slot="trigger" size="small" type="primary">select file</el-button></el-upload>
    ]
  },
  renderCell (h, editRender, { row, column }) {
    return [
      <span>{ row[column.property] }</span>
    ]
  }
})

```

**Comment by xuliangzhan** [comment]
Sorry I'm, because the el-upload needs to cooperate with many events, and the requirements of each project may be different, I think it should not be supported, and it is easier to customize with the renderer

**Comment by hasbug** [comment]
@xuliangzhan 类似这种的话，我要引入某个element-ui的组件，加入存在一个click，那事件怎么写呢？@click好像不行。
