### ISSUE TITLE
Elseclet中的options不支持响应数据传入吗？

### ISSUE THREAD

**Issue by hasbug** [xuliangzhan/vxe-table-plugin-element#6]
这个下拉项时异步向后端请求的，已经取到并存入data的selectArr中，也在options中配置了this.selectArr,但下拉选框无数据。

**Comment by xuliangzhan** [comment]
https://xuliangzhan_admin.gitee.io/vxe-table/#/table/grid/edit

**Comment by hasbug** [comment]
这个例子我也看过了，但好像不是Elselect的。

**Comment by hasbug** [comment]
我明白了，要找到对应column来做更新，这有点繁琐哦。
