### ISSUE TITLE
renderOptions 能否增加disabled项

### ISSUE THREAD

**Issue by yxhlcl** [xuliangzhan/vxe-table-plugin-element#7]
function renderOptions(h, options, optionProps) {
  var labelProp = optionProps.label || 'label';
  var valueProp = optionProps.value || 'value';
  ++var disabledProp = optionProps.disabled || 'disabled';
  return _xeUtils["default"].map(options, function (item, index) {
    return h('el-option', {
      props: {
        value: item[valueProp],
        label: item[labelProp],
        ++disabled:item[disabledProp]
      },
      key: index
    });
  });
}
在编辑表格时，不同的行，允许选择的值可能不同，通过disabled禁用不允许的值

**Comment by xuliangzhan** [comment]
这个已经可以支持了

**Comment by wind007** [comment]
diasabled 跟每一行有关系，这个disabled 应该是动态的，现在根据prop.options这里固定了，是否考虑增加一个 filterOptions的函数？
