### ISSUE TITLE
时间选择器的bug

### ISSUE THREAD

**Issue by DoveAz** [xuliangzhan/vxe-table-plugin-element#9]
说明
点击时间选择器下拉中的时或分、下拉面板会消失、时间没有正确被设置

复现
https://jsrun.pro/dwbKp/edit

**Comment by xuliangzhan** [comment]
你应该先检查字段名是否有定义

**Comment by DoveAz** [comment]
字段是定义了的。昨天那个复现地址不对，我是在你的例子上改的，鼠标滚轮滚动时间都可以设置成功，鼠标点就不行
https://jsrun.pro/iaWKp/edit

**Comment by xuliangzhan** [comment]
建议更新到最新试下
